// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vald-origin/apis/proto/v1/vald/insert.proto

package vald

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	payload "github.com/vdaas/vald-client-go/v1/payload"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("vald-origin/apis/proto/v1/vald/insert.proto", fileDescriptor_5321a447f70f8fff)
}
func init() {
	golang_proto.RegisterFile("vald-origin/apis/proto/v1/vald/insert.proto", fileDescriptor_5321a447f70f8fff)
}

var fileDescriptor_5321a447f70f8fff = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x35, 0x3b, 0x6c, 0x50, 0x77, 0x90, 0x82, 0x97, 0x4e, 0x2a, 0xd6, 0x83, 0x32, 0x59, 0xe2,
	0xf4, 0x20, 0xec, 0xb8, 0x9b, 0xa0, 0x28, 0x0e, 0x3d, 0x78, 0x4b, 0xdb, 0x18, 0x23, 0x5d, 0xbf,
	0xda, 0xa4, 0x05, 0xaf, 0xfe, 0x05, 0x7f, 0x80, 0x7f, 0xc5, 0xe3, 0x8e, 0x82, 0x7f, 0x40, 0x3a,
	0x7f, 0x88, 0x24, 0x69, 0xc7, 0x94, 0x21, 0x9e, 0xfa, 0xfa, 0x7d, 0xef, 0xbd, 0xbc, 0xf0, 0xe2,
	0x1c, 0x94, 0x34, 0x89, 0x07, 0x90, 0x0b, 0x2e, 0x52, 0x42, 0x33, 0x21, 0x49, 0x96, 0x83, 0x02,
	0x52, 0x0e, 0x89, 0xde, 0x10, 0x91, 0x4a, 0x96, 0x2b, 0x6c, 0x86, 0x6e, 0x47, 0x8f, 0x70, 0x39,
	0xf4, 0x76, 0x7f, 0x32, 0x33, 0xfa, 0x94, 0x00, 0x8d, 0x9b, 0xaf, 0x65, 0x7b, 0x03, 0x2e, 0xd4,
	0x7d, 0x11, 0xe2, 0x08, 0xa6, 0x84, 0x03, 0x07, 0xcb, 0x0f, 0x8b, 0x3b, 0xf3, 0x67, 0xc5, 0x1a,
	0xd5, 0xf4, 0x93, 0xdf, 0x74, 0x0e, 0xc0, 0x13, 0x66, 0x4e, 0xb2, 0x50, 0xe7, 0x23, 0x34, 0x4d,
	0x41, 0x51, 0x25, 0x20, 0x95, 0x56, 0x78, 0xf4, 0xda, 0x72, 0xda, 0xa7, 0x26, 0xa6, 0x7b, 0xbd,
	0x40, 0x1e, 0x6e, 0xc2, 0x94, 0x43, 0x6c, 0x67, 0xf8, 0x8a, 0x3d, 0x16, 0x4c, 0x2a, 0xaf, 0xb7,
	0xbc, 0xbb, 0x08, 0x1f, 0x58, 0xa4, 0xf0, 0x19, 0x44, 0xc6, 0x34, 0x70, 0x9f, 0x3f, 0xbe, 0x5e,
	0x5a, 0xdd, 0xa0, 0x53, 0x5f, 0x7d, 0x84, 0xfa, 0xee, 0xc4, 0xe9, 0x4e, 0x54, 0xce, 0xe8, 0xf4,
	0x1f, 0xe6, 0x3b, 0x2b, 0xcc, 0xad, 0x78, 0x71, 0xc4, 0xda, 0x3e, 0x3a, 0x44, 0xae, 0x70, 0xd6,
	0xcf, 0x8b, 0x44, 0x89, 0xda, 0x73, 0x7b, 0x85, 0xa7, 0xd9, 0x37, 0xc6, 0x5b, 0x7f, 0xa4, 0x96,
	0x41, 0xcf, 0xc4, 0xde, 0x0c, 0x36, 0xea, 0xd8, 0x64, 0xaa, 0xb5, 0x59, 0xc2, 0x46, 0xa8, 0x3f,
	0xe6, 0xb3, 0xca, 0x47, 0xef, 0x95, 0x8f, 0x3e, 0x2b, 0x1f, 0xbd, 0xcd, 0x7d, 0x34, 0x9b, 0xfb,
	0xc8, 0xf1, 0x20, 0xe7, 0xb8, 0x8c, 0x29, 0x95, 0xd8, 0xf4, 0x4a, 0x33, 0xa1, 0xad, 0x35, 0x1e,
	0x3b, 0x37, 0x34, 0x89, 0x6d, 0x8a, 0x4b, 0x74, 0xbb, 0xb7, 0x54, 0x8d, 0x11, 0xd8, 0xb7, 0x61,
	0xab, 0xc9, 0xb3, 0xa8, 0x79, 0x2d, 0x61, 0xdb, 0x34, 0x72, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x4a, 0x09, 0x41, 0x36, 0x56, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InsertClient is the client API for Insert service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InsertClient interface {
	Insert(ctx context.Context, in *payload.Insert_Request, opts ...grpc.CallOption) (*payload.Object_Location, error)
	StreamInsert(ctx context.Context, opts ...grpc.CallOption) (Insert_StreamInsertClient, error)
	MultiInsert(ctx context.Context, in *payload.Insert_MultiRequest, opts ...grpc.CallOption) (*payload.Object_Locations, error)
}

type insertClient struct {
	cc *grpc.ClientConn
}

func NewInsertClient(cc *grpc.ClientConn) InsertClient {
	return &insertClient{cc}
}

func (c *insertClient) Insert(ctx context.Context, in *payload.Insert_Request, opts ...grpc.CallOption) (*payload.Object_Location, error) {
	out := new(payload.Object_Location)
	err := c.cc.Invoke(ctx, "/vald.v1.Insert/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insertClient) StreamInsert(ctx context.Context, opts ...grpc.CallOption) (Insert_StreamInsertClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Insert_serviceDesc.Streams[0], "/vald.v1.Insert/StreamInsert", opts...)
	if err != nil {
		return nil, err
	}
	x := &insertStreamInsertClient{stream}
	return x, nil
}

type Insert_StreamInsertClient interface {
	Send(*payload.Insert_Request) error
	Recv() (*payload.Object_StreamLocation, error)
	grpc.ClientStream
}

type insertStreamInsertClient struct {
	grpc.ClientStream
}

func (x *insertStreamInsertClient) Send(m *payload.Insert_Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *insertStreamInsertClient) Recv() (*payload.Object_StreamLocation, error) {
	m := new(payload.Object_StreamLocation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *insertClient) MultiInsert(ctx context.Context, in *payload.Insert_MultiRequest, opts ...grpc.CallOption) (*payload.Object_Locations, error) {
	out := new(payload.Object_Locations)
	err := c.cc.Invoke(ctx, "/vald.v1.Insert/MultiInsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsertServer is the server API for Insert service.
type InsertServer interface {
	Insert(context.Context, *payload.Insert_Request) (*payload.Object_Location, error)
	StreamInsert(Insert_StreamInsertServer) error
	MultiInsert(context.Context, *payload.Insert_MultiRequest) (*payload.Object_Locations, error)
}

// UnimplementedInsertServer can be embedded to have forward compatible implementations.
type UnimplementedInsertServer struct {
}

func (*UnimplementedInsertServer) Insert(ctx context.Context, req *payload.Insert_Request) (*payload.Object_Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (*UnimplementedInsertServer) StreamInsert(srv Insert_StreamInsertServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamInsert not implemented")
}
func (*UnimplementedInsertServer) MultiInsert(ctx context.Context, req *payload.Insert_MultiRequest) (*payload.Object_Locations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiInsert not implemented")
}

func RegisterInsertServer(s *grpc.Server, srv InsertServer) {
	s.RegisterService(&_Insert_serviceDesc, srv)
}

func _Insert_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Insert_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsertServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Insert/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsertServer).Insert(ctx, req.(*payload.Insert_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Insert_StreamInsert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InsertServer).StreamInsert(&insertStreamInsertServer{stream})
}

type Insert_StreamInsertServer interface {
	Send(*payload.Object_StreamLocation) error
	Recv() (*payload.Insert_Request, error)
	grpc.ServerStream
}

type insertStreamInsertServer struct {
	grpc.ServerStream
}

func (x *insertStreamInsertServer) Send(m *payload.Object_StreamLocation) error {
	return x.ServerStream.SendMsg(m)
}

func (x *insertStreamInsertServer) Recv() (*payload.Insert_Request, error) {
	m := new(payload.Insert_Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Insert_MultiInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Insert_MultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsertServer).MultiInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Insert/MultiInsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsertServer).MultiInsert(ctx, req.(*payload.Insert_MultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Insert_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vald.v1.Insert",
	HandlerType: (*InsertServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _Insert_Insert_Handler,
		},
		{
			MethodName: "MultiInsert",
			Handler:    _Insert_MultiInsert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInsert",
			Handler:       _Insert_StreamInsert_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vald-origin/apis/proto/v1/vald/insert.proto",
}
