// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vald-origin/apis/proto/v1/vald/object.proto

package vald

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	payload "github.com/vdaas/vald-client-go/v1/payload"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("vald-origin/apis/proto/v1/vald/object.proto", fileDescriptor_bb2a88f1f954e68b)
}
func init() {
	golang_proto.RegisterFile("vald-origin/apis/proto/v1/vald/object.proto", fileDescriptor_bb2a88f1f954e68b)
}

var fileDescriptor_bb2a88f1f954e68b = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x31, 0x4b, 0xf4, 0x40,
	0x10, 0xfd, 0xf6, 0x2b, 0x4e, 0x5c, 0x44, 0x21, 0x68, 0x61, 0x8a, 0x08, 0x5a, 0x28, 0xc8, 0xed,
	0x7a, 0x5a, 0xd8, 0x1f, 0x8a, 0x08, 0xc2, 0x09, 0x07, 0x57, 0xd8, 0x6d, 0x92, 0x75, 0x5d, 0xc9,
	0x65, 0xc2, 0x66, 0x2f, 0x28, 0x62, 0xe3, 0x5f, 0xf0, 0x0f, 0x59, 0x5e, 0x29, 0xf8, 0x07, 0xe4,
	0xce, 0x9f, 0x61, 0x21, 0xbb, 0x93, 0xc0, 0x29, 0x11, 0xab, 0x4c, 0xde, 0xbc, 0xf7, 0x66, 0x78,
	0xb3, 0x74, 0xbf, 0x12, 0x59, 0xda, 0x05, 0xa3, 0x95, 0xce, 0xb9, 0x28, 0x74, 0xc9, 0x0b, 0x03,
	0x16, 0x78, 0xd5, 0xe3, 0xae, 0xc3, 0x21, 0xbe, 0x95, 0x89, 0x65, 0x1e, 0x0c, 0x96, 0x1c, 0xc4,
	0xaa, 0x5e, 0xb8, 0xf3, 0x9d, 0x59, 0x88, 0xfb, 0x0c, 0x44, 0xda, 0x7c, 0x91, 0x1d, 0x76, 0x95,
	0xb6, 0x37, 0x93, 0x98, 0x25, 0x30, 0xe6, 0x0a, 0x14, 0x20, 0x3f, 0x9e, 0x5c, 0xfb, 0x3f, 0x14,
	0xbb, 0xaa, 0xa6, 0x1f, 0xff, 0xa4, 0x2b, 0x00, 0x95, 0x49, 0x3f, 0x09, 0x4b, 0xb7, 0x1f, 0x17,
	0x79, 0x0e, 0x56, 0x58, 0x0d, 0x79, 0x89, 0xc2, 0xc3, 0x4f, 0x42, 0x3b, 0x03, 0xbf, 0x66, 0x70,
	0x41, 0x3b, 0xa7, 0x77, 0xba, 0xb4, 0x65, 0xb0, 0xc1, 0x9a, 0x65, 0xaa, 0x1e, 0xc3, 0x2e, 0x3b,
	0x3f, 0x09, 0xdb, 0xe1, 0xed, 0xf5, 0xa7, 0xb7, 0x8f, 0xe7, 0xff, 0xab, 0xc1, 0x0a, 0x97, 0x5e,
	0xce, 0x1f, 0x74, 0xfa, 0x18, 0x0c, 0xe9, 0xf2, 0x99, 0xb4, 0xb5, 0xf5, 0x2f, 0x86, 0x9b, 0x2d,
	0xf0, 0x48, 0x26, 0x16, 0xcc, 0x82, 0x29, 0x86, 0x88, 0xa6, 0x03, 0xba, 0x36, 0xb4, 0x46, 0x8a,
	0xf1, 0x9f, 0xd6, 0x5b, 0x2d, 0x30, 0x4a, 0xeb, 0x01, 0xff, 0xf6, 0xc8, 0x01, 0xe9, 0xab, 0xe9,
	0x2c, 0x22, 0xaf, 0xb3, 0x88, 0xbc, 0xcf, 0x22, 0xf2, 0x32, 0x8f, 0xc8, 0x74, 0x1e, 0x11, 0x1a,
	0x82, 0x51, 0xac, 0x4a, 0x85, 0x28, 0x99, 0x3f, 0x9a, 0x28, 0xb4, 0xb3, 0x71, 0x75, 0x9f, 0x8e,
	0x44, 0x96, 0xa2, 0xe1, 0x25, 0xb9, 0xda, 0x5d, 0xc8, 0xdd, 0x0b, 0xf0, 0xf0, 0x98, 0xbb, 0x29,
	0x92, 0xe6, 0x29, 0xc4, 0x1d, 0x1f, 0xf7, 0xd1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xf5,
	0x69, 0x65, 0x33, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ObjectClient is the client API for Object service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObjectClient interface {
	Exists(ctx context.Context, in *payload.Object_ID, opts ...grpc.CallOption) (*payload.Object_ID, error)
	GetObject(ctx context.Context, in *payload.Object_ID, opts ...grpc.CallOption) (*payload.Object_Vector, error)
	StreamGetObject(ctx context.Context, opts ...grpc.CallOption) (Object_StreamGetObjectClient, error)
}

type objectClient struct {
	cc *grpc.ClientConn
}

func NewObjectClient(cc *grpc.ClientConn) ObjectClient {
	return &objectClient{cc}
}

func (c *objectClient) Exists(ctx context.Context, in *payload.Object_ID, opts ...grpc.CallOption) (*payload.Object_ID, error) {
	out := new(payload.Object_ID)
	err := c.cc.Invoke(ctx, "/vald.v1.Object/Exists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectClient) GetObject(ctx context.Context, in *payload.Object_ID, opts ...grpc.CallOption) (*payload.Object_Vector, error) {
	out := new(payload.Object_Vector)
	err := c.cc.Invoke(ctx, "/vald.v1.Object/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectClient) StreamGetObject(ctx context.Context, opts ...grpc.CallOption) (Object_StreamGetObjectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Object_serviceDesc.Streams[0], "/vald.v1.Object/StreamGetObject", opts...)
	if err != nil {
		return nil, err
	}
	x := &objectStreamGetObjectClient{stream}
	return x, nil
}

type Object_StreamGetObjectClient interface {
	Send(*payload.Object_ID) error
	Recv() (*payload.Object_StreamVector, error)
	grpc.ClientStream
}

type objectStreamGetObjectClient struct {
	grpc.ClientStream
}

func (x *objectStreamGetObjectClient) Send(m *payload.Object_ID) error {
	return x.ClientStream.SendMsg(m)
}

func (x *objectStreamGetObjectClient) Recv() (*payload.Object_StreamVector, error) {
	m := new(payload.Object_StreamVector)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ObjectServer is the server API for Object service.
type ObjectServer interface {
	Exists(context.Context, *payload.Object_ID) (*payload.Object_ID, error)
	GetObject(context.Context, *payload.Object_ID) (*payload.Object_Vector, error)
	StreamGetObject(Object_StreamGetObjectServer) error
}

// UnimplementedObjectServer can be embedded to have forward compatible implementations.
type UnimplementedObjectServer struct {
}

func (*UnimplementedObjectServer) Exists(ctx context.Context, req *payload.Object_ID) (*payload.Object_ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (*UnimplementedObjectServer) GetObject(ctx context.Context, req *payload.Object_ID) (*payload.Object_Vector, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (*UnimplementedObjectServer) StreamGetObject(srv Object_StreamGetObjectServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamGetObject not implemented")
}

func RegisterObjectServer(s *grpc.Server, srv ObjectServer) {
	s.RegisterService(&_Object_serviceDesc, srv)
}

func _Object_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Object_ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Object/Exists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectServer).Exists(ctx, req.(*payload.Object_ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Object_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Object_ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Object/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectServer).GetObject(ctx, req.(*payload.Object_ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Object_StreamGetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObjectServer).StreamGetObject(&objectStreamGetObjectServer{stream})
}

type Object_StreamGetObjectServer interface {
	Send(*payload.Object_StreamVector) error
	Recv() (*payload.Object_ID, error)
	grpc.ServerStream
}

type objectStreamGetObjectServer struct {
	grpc.ServerStream
}

func (x *objectStreamGetObjectServer) Send(m *payload.Object_StreamVector) error {
	return x.ServerStream.SendMsg(m)
}

func (x *objectStreamGetObjectServer) Recv() (*payload.Object_ID, error) {
	m := new(payload.Object_ID)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Object_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vald.v1.Object",
	HandlerType: (*ObjectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exists",
			Handler:    _Object_Exists_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _Object_GetObject_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGetObject",
			Handler:       _Object_StreamGetObject_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vald-origin/apis/proto/v1/vald/object.proto",
}
