// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vald-origin/apis/proto/v1/vald/remove.proto

package vald

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	payload "github.com/vdaas/vald-client-go/v1/payload"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("vald-origin/apis/proto/v1/vald/remove.proto", fileDescriptor_0720d43b3a1951df)
}

var fileDescriptor_0720d43b3a1951df = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0x27, 0x9b, 0xf9, 0x21, 0xbf, 0xab, 0x2e, 0xeb, 0x50, 0x61, 0x5c, 0x28, 0x88, 0x89,
	0xd5, 0x37, 0x18, 0xb7, 0x8e, 0xca, 0x08, 0x2e, 0xdc, 0xc8, 0x6d, 0x1b, 0x62, 0xa4, 0xed, 0x8d,
	0x49, 0x1a, 0xf0, 0x0d, 0x5d, 0xfa, 0x08, 0xd2, 0xb5, 0x0f, 0x21, 0x49, 0xa6, 0xa2, 0x20, 0x6e,
	0x5c, 0xe5, 0x72, 0xce, 0xbd, 0x5f, 0xe0, 0x1c, 0x7a, 0xe4, 0xa1, 0x6d, 0x8e, 0xd1, 0x28, 0xa9,
	0x7a, 0x0e, 0x5a, 0x59, 0xae, 0x0d, 0x3a, 0xe4, 0xbe, 0xe4, 0xc1, 0xe1, 0x46, 0x74, 0xe8, 0x05,
	0x8b, 0x62, 0xf6, 0x2f, 0x48, 0xcc, 0x97, 0xf9, 0xfe, 0xf7, 0x4d, 0x0d, 0xcf, 0x2d, 0x42, 0x33,
	0xbd, 0x69, 0x3b, 0x5f, 0x48, 0x44, 0xd9, 0x8a, 0x40, 0xe5, 0xd0, 0xf7, 0xe8, 0xc0, 0x29, 0xec,
	0x6d, 0x72, 0x4f, 0xdf, 0x09, 0x9d, 0x6f, 0x22, 0x3c, 0x3b, 0xff, 0x9c, 0x72, 0x36, 0x21, 0x7c,
	0xc9, 0x92, 0xc6, 0x36, 0xe2, 0x69, 0x10, 0xd6, 0xe5, 0xbb, 0x5f, 0xbd, 0xab, 0xea, 0x51, 0xd4,
	0x8e, 0x5d, 0x60, 0x1d, 0xa1, 0xcb, 0x59, 0xb6, 0xa6, 0x3b, 0x37, 0xce, 0x08, 0xe8, 0xfe, 0x8c,
	0x3a, 0x24, 0x27, 0x24, 0xbb, 0xa4, 0xff, 0xd7, 0x43, 0xeb, 0xd4, 0x96, 0xb6, 0xf7, 0x03, 0x6d,
	0xeb, 0x27, 0xe4, 0xe2, 0x17, 0xa4, 0x5d, 0xce, 0x56, 0xf7, 0x2f, 0x63, 0x41, 0x5e, 0xc7, 0x82,
	0xbc, 0x8d, 0x05, 0xa1, 0x39, 0x1a, 0xc9, 0x7c, 0x03, 0x60, 0x59, 0x8c, 0x14, 0xb4, 0x0a, 0x77,
	0x61, 0x5e, 0xd1, 0x5b, 0x68, 0x9b, 0xf4, 0xc5, 0x35, 0xb9, 0x3b, 0x90, 0xca, 0x3d, 0x0c, 0x15,
	0xab, 0xb1, 0xe3, 0xf1, 0x20, 0xd5, 0x12, 0xf3, 0x97, 0x46, 0xd7, 0x53, 0x51, 0xd5, 0x3c, 0xc6,
	0x7a, 0xf6, 0x11, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x10, 0xa7, 0x1b, 0xd1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoveClient is the client API for Remove service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoveClient interface {
	Remove(ctx context.Context, in *payload.Remove_Request, opts ...grpc.CallOption) (*payload.Object_Location, error)
	StreamRemove(ctx context.Context, opts ...grpc.CallOption) (Remove_StreamRemoveClient, error)
	MultiRemove(ctx context.Context, in *payload.Remove_MultiRequest, opts ...grpc.CallOption) (*payload.Object_Locations, error)
}

type removeClient struct {
	cc *grpc.ClientConn
}

func NewRemoveClient(cc *grpc.ClientConn) RemoveClient {
	return &removeClient{cc}
}

func (c *removeClient) Remove(ctx context.Context, in *payload.Remove_Request, opts ...grpc.CallOption) (*payload.Object_Location, error) {
	out := new(payload.Object_Location)
	err := c.cc.Invoke(ctx, "/vald.v1.Remove/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *removeClient) StreamRemove(ctx context.Context, opts ...grpc.CallOption) (Remove_StreamRemoveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Remove_serviceDesc.Streams[0], "/vald.v1.Remove/StreamRemove", opts...)
	if err != nil {
		return nil, err
	}
	x := &removeStreamRemoveClient{stream}
	return x, nil
}

type Remove_StreamRemoveClient interface {
	Send(*payload.Remove_Request) error
	Recv() (*payload.Object_Location, error)
	grpc.ClientStream
}

type removeStreamRemoveClient struct {
	grpc.ClientStream
}

func (x *removeStreamRemoveClient) Send(m *payload.Remove_Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *removeStreamRemoveClient) Recv() (*payload.Object_Location, error) {
	m := new(payload.Object_Location)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *removeClient) MultiRemove(ctx context.Context, in *payload.Remove_MultiRequest, opts ...grpc.CallOption) (*payload.Object_Locations, error) {
	out := new(payload.Object_Locations)
	err := c.cc.Invoke(ctx, "/vald.v1.Remove/MultiRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoveServer is the server API for Remove service.
type RemoveServer interface {
	Remove(context.Context, *payload.Remove_Request) (*payload.Object_Location, error)
	StreamRemove(Remove_StreamRemoveServer) error
	MultiRemove(context.Context, *payload.Remove_MultiRequest) (*payload.Object_Locations, error)
}

// UnimplementedRemoveServer can be embedded to have forward compatible implementations.
type UnimplementedRemoveServer struct {
}

func (*UnimplementedRemoveServer) Remove(ctx context.Context, req *payload.Remove_Request) (*payload.Object_Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedRemoveServer) StreamRemove(srv Remove_StreamRemoveServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRemove not implemented")
}
func (*UnimplementedRemoveServer) MultiRemove(ctx context.Context, req *payload.Remove_MultiRequest) (*payload.Object_Locations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiRemove not implemented")
}

func RegisterRemoveServer(s *grpc.Server, srv RemoveServer) {
	s.RegisterService(&_Remove_serviceDesc, srv)
}

func _Remove_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Remove_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoveServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Remove/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoveServer).Remove(ctx, req.(*payload.Remove_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remove_StreamRemove_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoveServer).StreamRemove(&removeStreamRemoveServer{stream})
}

type Remove_StreamRemoveServer interface {
	Send(*payload.Object_Location) error
	Recv() (*payload.Remove_Request, error)
	grpc.ServerStream
}

type removeStreamRemoveServer struct {
	grpc.ServerStream
}

func (x *removeStreamRemoveServer) Send(m *payload.Object_Location) error {
	return x.ServerStream.SendMsg(m)
}

func (x *removeStreamRemoveServer) Recv() (*payload.Remove_Request, error) {
	m := new(payload.Remove_Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Remove_MultiRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Remove_MultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoveServer).MultiRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Remove/MultiRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoveServer).MultiRemove(ctx, req.(*payload.Remove_MultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Remove_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vald.v1.Remove",
	HandlerType: (*RemoveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Remove",
			Handler:    _Remove_Remove_Handler,
		},
		{
			MethodName: "MultiRemove",
			Handler:    _Remove_MultiRemove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRemove",
			Handler:       _Remove_StreamRemove_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vald-origin/apis/proto/v1/vald/remove.proto",
}
