// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vald-origin/apis/proto/v1/vald/update.proto

package vald

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	payload "github.com/vdaas/vald-client-go/v1/payload"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("vald-origin/apis/proto/v1/vald/update.proto", fileDescriptor_1bfcb9e8962a90fa)
}

var fileDescriptor_1bfcb9e8962a90fa = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x37, 0x1e, 0x76, 0x21, 0xee, 0xa9, 0xc7, 0xba, 0xac, 0x50, 0x0f, 0x8a, 0x62, 0x62,
	0xf5, 0xe6, 0x71, 0xcf, 0xae, 0x8a, 0xb2, 0x1e, 0xbc, 0xc8, 0xb4, 0x0d, 0x31, 0xd2, 0xed, 0xc4,
	0x36, 0x0d, 0x78, 0xf5, 0x15, 0x7c, 0x29, 0x8f, 0x82, 0x2f, 0x20, 0xc5, 0xe7, 0x10, 0x49, 0xb2,
	0x15, 0x05, 0xf1, 0xe2, 0x29, 0xc3, 0xff, 0xcf, 0x7c, 0x19, 0xe6, 0xa7, 0x7b, 0x16, 0xca, 0x62,
	0x1f, 0x6b, 0x25, 0x55, 0xc5, 0x41, 0xab, 0x86, 0xeb, 0x1a, 0x0d, 0x72, 0x9b, 0x72, 0xe7, 0xf0,
	0x56, 0x17, 0x60, 0x04, 0xf3, 0x62, 0x34, 0x72, 0x12, 0xb3, 0x69, 0xbc, 0xf5, 0xb3, 0x53, 0xc3,
	0x43, 0x89, 0x50, 0xf4, 0x6f, 0xe8, 0x8e, 0x27, 0x12, 0x51, 0x96, 0xc2, 0x51, 0x39, 0x54, 0x15,
	0x1a, 0x30, 0x0a, 0xab, 0x26, 0xb8, 0x87, 0x1f, 0x84, 0x0e, 0x17, 0x1e, 0x1e, 0x2d, 0xbe, 0xaa,
	0x98, 0xf5, 0x08, 0x9b, 0xb2, 0xa0, 0xb1, 0x0b, 0x71, 0xdf, 0x8a, 0xc6, 0xc4, 0x1b, 0xdf, 0xbd,
	0xb3, 0xec, 0x4e, 0xe4, 0x86, 0x9d, 0x60, 0xee, 0xa1, 0x49, 0xf4, 0xf8, 0xfa, 0xfe, 0xb4, 0x36,
	0x4e, 0x46, 0xab, 0x85, 0x8f, 0xc9, 0x6e, 0x34, 0xa7, 0xe3, 0x4b, 0x53, 0x0b, 0x58, 0xfe, 0x17,
	0x3e, 0xd8, 0x21, 0x07, 0x24, 0x3a, 0xa5, 0xeb, 0xf3, 0xb6, 0x34, 0x6a, 0x45, 0xdb, 0xfc, 0x85,
	0xe6, 0xfd, 0x1e, 0x39, 0xf9, 0x03, 0xd9, 0x24, 0x83, 0xd9, 0xcd, 0x73, 0x37, 0x25, 0x2f, 0xdd,
	0x94, 0xbc, 0x75, 0x53, 0x42, 0x63, 0xac, 0x25, 0xb3, 0x05, 0x40, 0xc3, 0xfc, 0x91, 0x41, 0x2b,
	0x37, 0xe7, 0xea, 0x19, 0xbd, 0x82, 0xb2, 0x08, 0x5f, 0x9c, 0x93, 0xeb, 0x6d, 0xa9, 0xcc, 0x6d,
	0x9b, 0xb1, 0x1c, 0x97, 0xdc, 0x0f, 0x84, 0xa0, 0x7c, 0x22, 0xb2, 0xd6, 0x79, 0x1f, 0x5d, 0x36,
	0xf4, 0x87, 0x3e, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x97, 0xab, 0x11, 0xe3, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UpdateClient is the client API for Update service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UpdateClient interface {
	Update(ctx context.Context, in *payload.Update_Request, opts ...grpc.CallOption) (*payload.Object_Location, error)
	StreamUpdate(ctx context.Context, opts ...grpc.CallOption) (Update_StreamUpdateClient, error)
	MultiUpdate(ctx context.Context, in *payload.Update_MultiRequest, opts ...grpc.CallOption) (*payload.Object_Locations, error)
}

type updateClient struct {
	cc *grpc.ClientConn
}

func NewUpdateClient(cc *grpc.ClientConn) UpdateClient {
	return &updateClient{cc}
}

func (c *updateClient) Update(ctx context.Context, in *payload.Update_Request, opts ...grpc.CallOption) (*payload.Object_Location, error) {
	out := new(payload.Object_Location)
	err := c.cc.Invoke(ctx, "/vald.v1.Update/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) StreamUpdate(ctx context.Context, opts ...grpc.CallOption) (Update_StreamUpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Update_serviceDesc.Streams[0], "/vald.v1.Update/StreamUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &updateStreamUpdateClient{stream}
	return x, nil
}

type Update_StreamUpdateClient interface {
	Send(*payload.Update_Request) error
	Recv() (*payload.Object_Location, error)
	grpc.ClientStream
}

type updateStreamUpdateClient struct {
	grpc.ClientStream
}

func (x *updateStreamUpdateClient) Send(m *payload.Update_Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *updateStreamUpdateClient) Recv() (*payload.Object_Location, error) {
	m := new(payload.Object_Location)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *updateClient) MultiUpdate(ctx context.Context, in *payload.Update_MultiRequest, opts ...grpc.CallOption) (*payload.Object_Locations, error) {
	out := new(payload.Object_Locations)
	err := c.cc.Invoke(ctx, "/vald.v1.Update/MultiUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateServer is the server API for Update service.
type UpdateServer interface {
	Update(context.Context, *payload.Update_Request) (*payload.Object_Location, error)
	StreamUpdate(Update_StreamUpdateServer) error
	MultiUpdate(context.Context, *payload.Update_MultiRequest) (*payload.Object_Locations, error)
}

// UnimplementedUpdateServer can be embedded to have forward compatible implementations.
type UnimplementedUpdateServer struct {
}

func (*UnimplementedUpdateServer) Update(ctx context.Context, req *payload.Update_Request) (*payload.Object_Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUpdateServer) StreamUpdate(srv Update_StreamUpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamUpdate not implemented")
}
func (*UnimplementedUpdateServer) MultiUpdate(ctx context.Context, req *payload.Update_MultiRequest) (*payload.Object_Locations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiUpdate not implemented")
}

func RegisterUpdateServer(s *grpc.Server, srv UpdateServer) {
	s.RegisterService(&_Update_serviceDesc, srv)
}

func _Update_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Update_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Update/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).Update(ctx, req.(*payload.Update_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_StreamUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UpdateServer).StreamUpdate(&updateStreamUpdateServer{stream})
}

type Update_StreamUpdateServer interface {
	Send(*payload.Object_Location) error
	Recv() (*payload.Update_Request, error)
	grpc.ServerStream
}

type updateStreamUpdateServer struct {
	grpc.ServerStream
}

func (x *updateStreamUpdateServer) Send(m *payload.Object_Location) error {
	return x.ServerStream.SendMsg(m)
}

func (x *updateStreamUpdateServer) Recv() (*payload.Update_Request, error) {
	m := new(payload.Update_Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Update_MultiUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Update_MultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).MultiUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Update/MultiUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).MultiUpdate(ctx, req.(*payload.Update_MultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Update_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vald.v1.Update",
	HandlerType: (*UpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _Update_Update_Handler,
		},
		{
			MethodName: "MultiUpdate",
			Handler:    _Update_MultiUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpdate",
			Handler:       _Update_StreamUpdate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vald-origin/apis/proto/v1/vald/update.proto",
}
