// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vald-origin/apis/proto/v1/vald/upsert.proto

package vald

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	payload "github.com/vdaas/vald-client-go/v1/payload"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("vald-origin/apis/proto/v1/vald/upsert.proto", fileDescriptor_a4b0605ad5728fdb)
}

var fileDescriptor_a4b0605ad5728fdb = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0x33, 0x31,
	0x14, 0x85, 0xff, 0x74, 0xd1, 0x42, 0xfe, 0x2e, 0x64, 0xc0, 0xcd, 0xb4, 0x54, 0x1c, 0x17, 0x4a,
	0xc5, 0xc4, 0xea, 0xae, 0xcb, 0xae, 0x15, 0xc5, 0x52, 0x17, 0x6e, 0x24, 0x33, 0x13, 0x62, 0x24,
	0x33, 0x89, 0x49, 0x66, 0xc0, 0xad, 0xaf, 0xe0, 0x03, 0xf8, 0x3a, 0x2e, 0x05, 0x5f, 0x40, 0x06,
	0x1f, 0x44, 0x92, 0xcc, 0x14, 0x85, 0x22, 0xae, 0x12, 0xee, 0xb9, 0xe7, 0xbb, 0x07, 0x0e, 0x3c,
	0xac, 0x89, 0xc8, 0x8f, 0xa4, 0xe6, 0x8c, 0x97, 0x98, 0x28, 0x6e, 0xb0, 0xd2, 0xd2, 0x4a, 0x5c,
	0xcf, 0xb0, 0x53, 0x70, 0xa5, 0x0c, 0xd5, 0x16, 0xf9, 0x61, 0x34, 0x70, 0x23, 0x54, 0xcf, 0xe2,
	0xbd, 0x9f, 0x9b, 0x8a, 0x3c, 0x0a, 0x49, 0xf2, 0xee, 0x0d, 0xdb, 0xf1, 0x98, 0x49, 0xc9, 0x04,
	0x75, 0x54, 0x4c, 0xca, 0x52, 0x5a, 0x62, 0xb9, 0x2c, 0x4d, 0x50, 0x4f, 0x5e, 0x7a, 0xb0, 0xbf,
	0xf2, 0xf0, 0x68, 0xb5, 0xfe, 0xc5, 0xa8, 0x43, 0xd4, 0x33, 0x14, 0x66, 0xe8, 0x8a, 0x3e, 0x54,
	0xd4, 0xd8, 0x78, 0xf4, 0x5d, 0xbb, 0x48, 0xef, 0x69, 0x66, 0xd1, 0x99, 0xcc, 0x3c, 0x34, 0x89,
	0x9e, 0xde, 0x3f, 0x9f, 0x7b, 0xc3, 0x64, 0xd0, 0x06, 0x9e, 0x83, 0x69, 0xb4, 0x84, 0xc3, 0xa5,
	0xd5, 0x94, 0x14, 0x7f, 0x80, 0xef, 0x6e, 0x80, 0x07, 0xf3, 0xfa, 0xc4, 0xbf, 0x03, 0x70, 0x0c,
	0x22, 0x0e, 0xff, 0x9f, 0x57, 0xc2, 0xf2, 0x96, 0xb9, 0xb3, 0x81, 0xe9, 0xf5, 0x0e, 0x3c, 0xfe,
	0x25, 0xb5, 0x49, 0x46, 0x3e, 0xf6, 0x76, 0xb2, 0xd5, 0xc6, 0xc6, 0x85, 0xf3, 0x2a, 0x41, 0xe7,
	0x60, 0xba, 0xb8, 0x7d, 0x6d, 0x26, 0xe0, 0xad, 0x99, 0x80, 0x8f, 0x66, 0x02, 0x60, 0x2c, 0x35,
	0x43, 0x75, 0x4e, 0x88, 0x41, 0xbe, 0x05, 0xa2, 0xb8, 0x43, 0xba, 0xff, 0x02, 0x5e, 0x13, 0x91,
	0x87, 0xeb, 0x97, 0xe0, 0x66, 0x9f, 0x71, 0x7b, 0x57, 0xa5, 0x28, 0x93, 0x05, 0xf6, 0x86, 0xd0,
	0xa4, 0xaf, 0x8c, 0x69, 0x95, 0x75, 0xdd, 0xa6, 0x7d, 0xdf, 0xc4, 0xe9, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc9, 0x70, 0x65, 0xca, 0x04, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UpsertClient is the client API for Upsert service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UpsertClient interface {
	Upsert(ctx context.Context, in *payload.Upsert_Request, opts ...grpc.CallOption) (*payload.Object_Location, error)
	StreamUpsert(ctx context.Context, opts ...grpc.CallOption) (Upsert_StreamUpsertClient, error)
	MultiUpsert(ctx context.Context, in *payload.Upsert_MultiRequest, opts ...grpc.CallOption) (*payload.Object_Locations, error)
}

type upsertClient struct {
	cc *grpc.ClientConn
}

func NewUpsertClient(cc *grpc.ClientConn) UpsertClient {
	return &upsertClient{cc}
}

func (c *upsertClient) Upsert(ctx context.Context, in *payload.Upsert_Request, opts ...grpc.CallOption) (*payload.Object_Location, error) {
	out := new(payload.Object_Location)
	err := c.cc.Invoke(ctx, "/vald.v1.Upsert/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upsertClient) StreamUpsert(ctx context.Context, opts ...grpc.CallOption) (Upsert_StreamUpsertClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Upsert_serviceDesc.Streams[0], "/vald.v1.Upsert/StreamUpsert", opts...)
	if err != nil {
		return nil, err
	}
	x := &upsertStreamUpsertClient{stream}
	return x, nil
}

type Upsert_StreamUpsertClient interface {
	Send(*payload.Upsert_Request) error
	Recv() (*payload.Object_StreamLocation, error)
	grpc.ClientStream
}

type upsertStreamUpsertClient struct {
	grpc.ClientStream
}

func (x *upsertStreamUpsertClient) Send(m *payload.Upsert_Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *upsertStreamUpsertClient) Recv() (*payload.Object_StreamLocation, error) {
	m := new(payload.Object_StreamLocation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *upsertClient) MultiUpsert(ctx context.Context, in *payload.Upsert_MultiRequest, opts ...grpc.CallOption) (*payload.Object_Locations, error) {
	out := new(payload.Object_Locations)
	err := c.cc.Invoke(ctx, "/vald.v1.Upsert/MultiUpsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpsertServer is the server API for Upsert service.
type UpsertServer interface {
	Upsert(context.Context, *payload.Upsert_Request) (*payload.Object_Location, error)
	StreamUpsert(Upsert_StreamUpsertServer) error
	MultiUpsert(context.Context, *payload.Upsert_MultiRequest) (*payload.Object_Locations, error)
}

// UnimplementedUpsertServer can be embedded to have forward compatible implementations.
type UnimplementedUpsertServer struct {
}

func (*UnimplementedUpsertServer) Upsert(ctx context.Context, req *payload.Upsert_Request) (*payload.Object_Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (*UnimplementedUpsertServer) StreamUpsert(srv Upsert_StreamUpsertServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamUpsert not implemented")
}
func (*UnimplementedUpsertServer) MultiUpsert(ctx context.Context, req *payload.Upsert_MultiRequest) (*payload.Object_Locations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiUpsert not implemented")
}

func RegisterUpsertServer(s *grpc.Server, srv UpsertServer) {
	s.RegisterService(&_Upsert_serviceDesc, srv)
}

func _Upsert_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Upsert_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsertServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Upsert/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsertServer).Upsert(ctx, req.(*payload.Upsert_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Upsert_StreamUpsert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UpsertServer).StreamUpsert(&upsertStreamUpsertServer{stream})
}

type Upsert_StreamUpsertServer interface {
	Send(*payload.Object_StreamLocation) error
	Recv() (*payload.Upsert_Request, error)
	grpc.ServerStream
}

type upsertStreamUpsertServer struct {
	grpc.ServerStream
}

func (x *upsertStreamUpsertServer) Send(m *payload.Object_StreamLocation) error {
	return x.ServerStream.SendMsg(m)
}

func (x *upsertStreamUpsertServer) Recv() (*payload.Upsert_Request, error) {
	m := new(payload.Upsert_Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Upsert_MultiUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Upsert_MultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsertServer).MultiUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vald.v1.Upsert/MultiUpsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsertServer).MultiUpsert(ctx, req.(*payload.Upsert_MultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Upsert_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vald.v1.Upsert",
	HandlerType: (*UpsertServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _Upsert_Upsert_Handler,
		},
		{
			MethodName: "MultiUpsert",
			Handler:    _Upsert_MultiUpsert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpsert",
			Handler:       _Upsert_StreamUpsert_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vald-origin/apis/proto/v1/vald/upsert.proto",
}
